import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { Geometry } from "../components/Geo";
import { useState } from "react";
import { MatCapButton } from "../components/MatCapButton";

export default function Home() {
  const [selectedMaterial, setSelectedMaterial] = useState<string>("default");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/threejspractice/favicon.ico" />
      </Head>
      <div className="px-4 md:px-12 lg:mx-auto lg:max-w-[1184px] h-full">
        <div className="h-8"></div>
        <div className="flex flex-row space-x-3">
          <div className="w-[900px] h-[600px] my-auto bg-black">
            <Canvas camera={{ fov: 50, position: [0, 2, 5] }} className="">
              <Geometry selectedMaterial={selectedMaterial} />
            </Canvas>
          </div>
          <div className="flex flex-col space-y-2">
            {[1, 2, 3, 4, 5, 6, 7, 8].map((number) => {
              return (
                <MatCapButton
                  key={number}
                  name={`matcap${number}`}
                  onClick={() => setSelectedMaterial(`${number}.png`)}
                />
              );
            })}
          </div>
        </div>
      </div>
    </>
  );
}
