import Head from "next/head";
import { Canvas } from "@react-three/fiber";
import { Geometry } from "../components/Geo";
import { useRef, useState } from "react";
import { Vector3 } from "three";
import cn from "classnames";
import styles from "../styles/index.module.css";

export default function Home() {
  const pointRef = useRef<HTMLDivElement>(null);
  const pointRef2 = useRef<HTMLDivElement>(null);

  const [points, setPoints] = useState<Vector3[]>([]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/threejspractice/favicon.ico" />
      </Head>
      <div className={cn(`flex mx-auto mt-[20px] w-[600px] h-[600px]`)}>
        <Canvas
          camera={{ fov: 50, position: [0, 2, 5] }}
          className="h-[800px] bg-slate-700"
        >
          <Geometry
            points={[
              {
                elementRef: pointRef,
                position: new Vector3(0.0, 0.0, 0.8),
              },
              {
                elementRef: pointRef2,
                position: new Vector3(0.4, 1.5, 0.0),
              },
            ]}
            setPoints={setPoints}
            currentPoints={points}
          />
        </Canvas>
        <div
          ref={pointRef}
          className={cn(
            styles.point,
            "w-5 h-5 rounded-full absolute top-1/2 left-1/2 bg-black/50 opacity-0 group"
          )}
        >
          <div className="relative text-white flex text-xs items-center leading-[20px] justify-center select-none">
            1
          </div>
          <div
            className={cn(
              "absolute top-[30px] w-[200px] left-[-100px] text-white bg-black/50 p-[5px] rounded-lg text-xs invisible group-hover:visible group-hover:transition"
            )}
          >
            Can this arrow be moved slightly to the right?
          </div>
        </div>
        <div
          ref={pointRef2}
          className={cn(
            styles.point,
            "w-5 h-5 rounded-full absolute top-1/2 left-1/2 bg-black/50 opacity-0 group"
          )}
        >
          <div className="relative text-white flex text-xs items-center leading-[20px] justify-center select-none">
            2
          </div>
          <div
            className={cn(
              "absolute top-[30px] w-[200px] left-[-100px] text-white bg-black/50 p-[5px] rounded-lg text-xs invisible group-hover:visible group-hover:transition"
            )}
          >
            Can this horn be a little pointier?
          </div>
        </div>

        {/* {points.map((point) => (
          <div
            key={point.x}
            className={cn(
              `w-5 h-5 rounded-full absolute top-1/2 left-1/2 bg-yellow-500`
            )}
            style={{ transform: `translate(${point.x}px, ${point.y}px)` }}
          />
        ))}
        <div
          className={cn(
            `w-5 h-5 rounded-full absolute top-1/2 left-1/2 bg-green-500`
          )}
        /> */}
      </div>
    </>
  );
}
